//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPA.DN.CoreUtil.Basic {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CoreStr {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CoreStr() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IPA.DN.CoreUtil.Basic.CoreStr", typeof(CoreStr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Item に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CMD_CT_STD_COLUMN_1 {
            get {
                return ResourceManager.GetString("CMD_CT_STD_COLUMN_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Value に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CMD_CT_STD_COLUMN_2 {
            get {
                return ResourceManager.GetString("CMD_CT_STD_COLUMN_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The date and time specification is invalid. \nThe date and time must be in the same format as &quot;2005/10/08 19:30:00&quot; where 6 integers are specified, representing year/month/day hour:minute:second separated by forward slashes, a space and then colons. Specify 4 digits for the year. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CMD_EVAL_DATE_TIME_FAILED {
            get {
                return ResourceManager.GetString("CMD_EVAL_DATE_TIME_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You must specify an integer that is not less than 1. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CMD_EVAL_INT {
            get {
                return ResourceManager.GetString("CMD_EVAL_INT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You must specify an integer in the range from %u to %u for the value. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CMD_EVAL_MIN_MAX {
            get {
                return ResourceManager.GetString("CMD_EVAL_MIN_MAX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You cannot make a blank specification. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CMD_EVAL_NOT_EMPTY {
            get {
                return ResourceManager.GetString("CMD_EVAL_NOT_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Port number is invalid. Specify a port number that is within the range of 1 to 65535. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CMD_EVAL_PORT {
            get {
                return ResourceManager.GetString("CMD_EVAL_PORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The string contains unusable characters. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CMD_EVAL_SAFE {
            get {
                return ResourceManager.GetString("CMD_EVAL_SAFE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   %S command - %s に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CMD_EXEC_MSG_NAME {
            get {
                return ResourceManager.GetString("CMD_EXEC_MSG_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The file name is not specified. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CMD_FILE_NAME_EMPTY {
            get {
                return ResourceManager.GetString("CMD_FILE_NAME_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot find specified file &quot;%s&quot;. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CMD_FILE_NOT_FOUND {
            get {
                return ResourceManager.GetString("CMD_FILE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You can use the following %u commands: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CMD_HELP_1 {
            get {
                return ResourceManager.GetString("CMD_HELP_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   To reference the usage for each command, input &quot;command name /?&quot; to view a help. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CMD_HELP_2 {
            get {
                return ResourceManager.GetString("CMD_HELP_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Parameters: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CMD_HELP_ARGS {
            get {
                return ResourceManager.GetString("CMD_HELP_ARGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Purpose: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CMD_HELP_DESCRIPTION {
            get {
                return ResourceManager.GetString("CMD_HELP_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Description: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CMD_HELP_HELP {
            get {
                return ResourceManager.GetString("CMD_HELP_HELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Help for command &quot;%S&quot; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CMD_HELP_TITLE {
            get {
                return ResourceManager.GetString("CMD_HELP_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Usage: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CMD_HELP_USAGE {
            get {
                return ResourceManager.GetString("CMD_HELP_USAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &quot;IP アドレス/サブネットマスク&quot; の形式で指定してください。
        ///IP アドレスは 192.168.0.1 のように 10 進数をドットで区切って指定します。サブネットマスクは 255.255.255.0 のように 10 進数をドットで区切って指定するか、24 のように先頭からのビット長を 10 進数で指定できます。
        ///単一のホストを指定するには、サブネットマスクを 255.255.255.255 または 32 として指定します。
        ///(例)
        /// 192.168.0.1/24
        /// 192.168.0.1/255.255.255.0
        ///192.168.0.5/255.255.255.255
        ///
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CMD_PARSE_IP_SUBNET_ERROR_1 {
            get {
                return ResourceManager.GetString("CMD_PARSE_IP_SUBNET_ERROR_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定された IP アドレスはネットワークアドレスではありません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CMD_PARSE_IP_SUBNET_ERROR_2 {
            get {
                return ResourceManager.GetString("CMD_PARSE_IP_SUBNET_ERROR_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enter a value:  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CMD_PROMPT {
            get {
                return ResourceManager.GetString("CMD_PROMPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Input the port number:  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CMD_PROPMT_PORT {
            get {
                return ResourceManager.GetString("CMD_PROPMT_PORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There is no description for this command. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CMD_UNKNOWM {
            get {
                return ResourceManager.GetString("CMD_UNKNOWM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There is no command execution example. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CMD_UNKNOWN_ARGS {
            get {
                return ResourceManager.GetString("CMD_UNKNOWN_ARGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There is no detailed description for this command. If you would like to know more detail about this command, please refer to the manual or online documentation. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CMD_UNKNOWN_HELP {
            get {
                return ResourceManager.GetString("CMD_UNKNOWN_HELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There is no description for this parameter. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CMD_UNKNOWN_PARAM {
            get {
                return ResourceManager.GetString("CMD_UNKNOWN_PARAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &quot;%S&quot;: The command-name is ambiguous. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CON_AMBIGIOUS_CMD {
            get {
                return ResourceManager.GetString("CON_AMBIGIOUS_CMD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The specified command name matches the following multiple commands. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CON_AMBIGIOUS_CMD_1 {
            get {
                return ResourceManager.GetString("CON_AMBIGIOUS_CMD_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please re-specify the command name more strictly. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CON_AMBIGIOUS_CMD_2 {
            get {
                return ResourceManager.GetString("CON_AMBIGIOUS_CMD_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &quot;%S&quot;: The parameter name is ambiguous. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CON_AMBIGIOUS_PARAM {
            get {
                return ResourceManager.GetString("CON_AMBIGIOUS_PARAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The specified parameter name matches with the following parameters that can be specified as a parameter of command &quot;%S&quot;. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CON_AMBIGIOUS_PARAM_1 {
            get {
                return ResourceManager.GetString("CON_AMBIGIOUS_PARAM_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please re-specify the parameter name more strictly. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CON_AMBIGIOUS_PARAM_2 {
            get {
                return ResourceManager.GetString("CON_AMBIGIOUS_PARAM_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error: Unable to open the specified input file &quot;%s&quot;. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CON_INFILE_ERROR {
            get {
                return ResourceManager.GetString("CON_INFILE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The commands written in the file &quot;%s&quot; will be used instead of input from keyboard. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CON_INFILE_START {
            get {
                return ResourceManager.GetString("CON_INFILE_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The parameter &quot;/%S&quot; has been specified. It is not possible to specify this parameter when using the command &quot;%S&quot;. Input &quot;%S /HELP&quot; to see the list of what parameters can be used. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CON_INVALID_PARAM {
            get {
                return ResourceManager.GetString("CON_INVALID_PARAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error: Unable to create the specified output file &quot;%s&quot;. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CON_OUTFILE_ERROR {
            get {
                return ResourceManager.GetString("CON_OUTFILE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The message output to the console will be saved in the file &quot;%s&quot;. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CON_OUTFILE_START {
            get {
                return ResourceManager.GetString("CON_OUTFILE_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &quot;%S&quot;: Command not found. You can use the HELP command to view a list of the available commands. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CON_UNKNOWN_CMD {
            get {
                return ResourceManager.GetString("CON_UNKNOWN_CMD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [EOF] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CON_USER_CANCEL {
            get {
                return ResourceManager.GetString("CON_USER_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The command was canceled. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CON_USER_CANCELED {
            get {
                return ResourceManager.GetString("CON_USER_CANCELED", resourceCulture);
            }
        }
    }
}
